add: menambahkan informasi branch
bellshade/Git pull request #2
Opened 2021-10-03 14:30 UTC by ezza022

2021-10-03 18:19 UTC, slowy07 requested changes
Terima kasih atas kontribusinya @ezza022, sebelumnya merge,bisakah kamu mengganti yng kami minta ?,terima kasih!

2021-10-03 18:19 UTC, slowy07 commented on README.md
> +git branch [nama_branch]
```suggestion
git branch nama_branch
```

2021-10-03 18:19 UTC, slowy07 commented on README.md
> +git checkout [nama_branch]
```suggestion
git checkout nama_branch
```

2021-10-03 18:45 UTC, slowy07 approved these changes
request @bellshade/docs-team

2021-10-04 02:28 UTC, nomadkode approved these changes

2021-10-04 12:01 UTC, hendraaagil approved these changes

2021-10-04 12:02 UTC, merged

2021-10-05 06:01 UTC, nomadkode commented
terima kasih @ezza022 sudah berkontribusi di bellshade. LGTM 🚀